# Use an official lightweight image of the C++ runtime
FROM gcc:latest

# Set the working directory in the container
WORKDIR /home/runner/work/Foobar-BIU/Foobar-BIU

# Copy the current directory contents into the container
COPY . .

# Compile the C++ code
RUN apt-get update; apt-get install -y build-essential cmake libgtest-dev
RUN cmake -B build -S .
RUN cmake --build build

# Specify the command to run on container startup
CMD ["./build/Foobar"]