# Use an official lightweight image of the C++ runtime
FROM gcc:latest

# Set the working directory in the container
WORKDIR /usr/src/Foobar-BIU

# Copy the current directory contents into the container
COPY . .

# Compile the C++ code
RUN sudo apt-get update; sudo apt-get install build-essential cmake libgtest-dev; cmake -B build -S .

RUN cmake --build build

# Specify the command to run on container startup
CMD ["./build/Foobar"]